/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=sms-worker/wrangler.toml --include-runtime=false sms-worker/worker-configuration.d.ts` (hash: adf4fbc7be5b15f95eed9cbe04a35e8f)
interface __BaseEnv_Env {
	WHATSAPP_PHONE: "972506102416";
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "WHATSAPP_PHONE">> {}
}
